version: '3'

volumes:
  db_volume:

services:

  db:
    image: mysql:8.0.23
    environment:
      - MYSQL_DATABASE=laravel9_sample_pj_db
      - MYSQL_USER=u
      - MYSQL_PASSWORD=p
      - MYSQL_ROOT_PASSWORD=p
      - TZ=Asia/Tokyo
      - BIND-ADDRESS=0.0.0.0
    volumes:
      - db_volume:/var/lib/mysql
    ports:
      - "33306:3306"
    tty: true
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_bin
      --sql-mode=NO_ENGINE_SUBSTITUTION
      --default-authentication-plugin=mysql_native_password

  laravel:
    build:
      context: ./
      dockerfile: ./docker_config/web/Dockerfile
    ports:
      - "443:443"
    volumes:
      - ./:/var/www/html/
      - ./docker_config/web/web.conf:/etc/apache2/sites-available/web.conf
      - ./docker_config/web/ssl/ssl.crt:${SSLCertificateFile}
      - ./docker_config/web/ssl/ssl.key:${SSLCertificateKeyFile}
    environment:
      - TZ=Asia/Tokyo
    working_dir: /var/www/html/
    tty: true
    env_file:
      - ./.env

  mailhog:
    image: "mailhog/mailhog"
    ports:
      - "8025:8025"
    tty: true

